# Generated by Django 5.2.5 on 2025-09-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('slots', models.PositiveIntegerField(default=5)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='BottleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('quantity_ml', models.PositiveIntegerField(default=0)),
                ('capacity_ml', models.PositiveIntegerField(default=1000)),
                ('last_refilled', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.ingredient')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_slots', to='machine.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='machine.machine')),
            ],
        ),
    ]
